global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/your_slack_api_token'
  opsgenie_api_url: 'https://api.opsgenie.com'
  smtp_smarthost: 'your_smtp_smarthost:587'
  smtp_from: 'your_smtp_from'
  smtp_auth_username: 'your_smtp_user'
  smtp_auth_password: 'your_smtp_pass'
templates:
- '/etc/alertmanager/template/*.tmpl'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'opsgenie'
receivers:
- name: 'opsgenie'
  opsgenie_configs:
    - send_resolved: true
      api_key: "apikey"
  email_configs:
  - to: 'your_alert_email_address'
    send_resolved: true
